package com.yassinecoding.gestiondestock.exception;

public enum ErrorCode {

    // we use the enum to define the error code
    ARTICLE_NOT_FOUND(1000),
    ARTICLE_NOT_VALID(1001),
    CATEGORY_NOT_FOUND(2000),
    CATEGORY_NOT_VALID(2001),
    CLIENT_NOT_FOUND(3000),
    CLIENT_NOT_VALID(3001),
    COMMANDE_CLIENT_NOT_FOUND(4000),
    COMMANDE_CLIENT_NOT_VALID(4001),
    COMMANDE_FOURNISSEUR_NOT_FOUND(5000),
    COMMANDE_FOURNISSEUR_NOT_VALID(5001),
    ENTREPRISE_NOT_FOUND(6000),
    ENTREPRISE_NOT_VALID(6001),
    FOURNISSEUR_NOT_FOUND(7000),
    FOURNISSEUR_NOT_VALID(7001),
    LIGNE_COMMANDE_CLIENT_NOT_FOUND(8000),
    LIGNE_COMMANDE_CLIENT_NOT_VALID(8001),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(9000),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_VALID(9001),
    LIGNE_VENTE_NOT_FOUND(10000),
    LIGNE_VENTE_NOT_VALID(10001),
    MVVT_STK_NOT_FOUND(11000),
    MVVT_STK_NOT_VALID(11001),
    UTILISATEUR_NOT_FOUND(12000),
    UTILISATEUR_NOT_VALID(12001),
    VENTES_NOT_FOUND(13000),
    VENTES_NOT_VALID(13001),
    BAD_REQUEST(14000),
    INVALID_FIELD(15000),
    INVALID_TYPE(16000);

    private final Integer code;

    // constructor for the enum ErrorCode
    ErrorCode(Integer code) {
        this.code = code;
    }

    // renvoyer le code de l'erreur
    public Integer getCode() {
        return code;
    }
}