spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionStock
    username: postgres
    password: Rayana2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
